################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.6
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : gtwizard_0_exdes.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7vx690t
## Package: ffg1761
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.


################################## Clock Constraints ##########################


####################### GT reference clock constraints #########################
 

create_clock -period 6.4 [get_ports Q3_CLK1_GTREFCLK_PAD_P_IN]


create_clock -name drpclk_in_i -period 10.0 [get_ports DRP_CLK_IN_P]

# User Clock Constraints
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/CLR}]
set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/D}]

################################# RefClk Location constraints #####################
#set_property LOC AK7 [get_ports  Q3_CLK1_GTREFCLK_PAD_N_IN ] 
#set_property LOC AK8 [get_ports  Q3_CLK1_GTREFCLK_PAD_P_IN ]
set_property PACKAGE_PIN AH8 [get_ports Q3_CLK1_GTREFCLK_PAD_P_IN]
set_property PACKAGE_PIN AH7 [get_ports Q3_CLK1_GTREFCLK_PAD_N_IN]

## LOC constrain for DRP_CLK_P/N 
set_property LOC H19 [get_ports  DRP_CLK_IN_P]
set_property LOC G18 [get_ports  DRP_CLK_IN_N]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DRP_CLK_IN_P]
set_property IOSTANDARD DIFF_SSTL15 [get_ports DRP_CLK_IN_N]

 
################################# mgt wrapper constraints #####################

##---------- Set placement for gt0_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X1Y12 [get_cells gtwizard_0_support_i/gtwizard_0_init_i/U0/gtwizard_0_i/gt0_gtwizard_0_i/gthe2_i]
##---------- Set placement for gt1_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X1Y13 [get_cells gtwizard_0_support_i/gtwizard_0_init_i/U0/gtwizard_0_i/gt1_gtwizard_0_i/gthe2_i]
##---------- Set placement for gt2_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X1Y14 [get_cells gtwizard_0_support_i/gtwizard_0_init_i/U0/gtwizard_0_i/gt2_gtwizard_0_i/gthe2_i]
##---------- Set placement for gt3_gth_wrapper_i/GTHE2_CHANNEL ------
set_property LOC GTHE2_CHANNEL_X1Y15 [get_cells gtwizard_0_support_i/gtwizard_0_init_i/U0/gtwizard_0_i/gt3_gtwizard_0_i/gthe2_i]

##---------- Set ASYNC_REG for flop which have async input ----------
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_check*system_reset_r_reg}]


#SI5324 - See page 32 of eval board pdf.
#set_property PACKAGE_PIN AU34 [get_ports SI5324_INT_ALM_LS]
#set_property IOSTANDARD LVCMOS18 [get_ports SI5324_INT_ALM_LS]
#set_property PACKAGE_PIN AH7 [get_ports SI5324_OUT_C_N]
#set_property PACKAGE_PIN AH8 [get_ports SI5324_OUT_C_P]

set_property PACKAGE_PIN AT36    [get_ports SI5324_RST_LS]
set_property IOSTANDARD LVCMOS18 [get_ports SI5324_RST_LS]

#set_output_delay -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports SI5324_RST_LS]
#set_output_delay -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports SI5324_RST_LS]

#set_input_delay -clock [get_clocks Clkif] -min 0.530 [get_ports DIN]
#set_input_delay -clock [get_clocks Clkif] -max 7.700 [get_ports DIN]
#set_output_delay -clock [get_clocks Clkif] -min -0.030 [get_ports DOUT]
#set_output_delay -clock [get_clocks Clkif] -max 1.800 [get_ports DOUT]

#SFP1
#set_property PACKAGE_PIN Y39            [get_ports {SFP_LOS[0]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_LOS[0]}]
set_property PACKAGE_PIN Y39            [get_ports SFP_LOS_0]
set_property IOSTANDARD LVCMOS18        [get_ports SFP_LOS_0]
#set_property PACKAGE_PIN AB42           [get_ports {SFP_MOD_DETECT[0]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_MOD_DETECT[0]}]
#set_property PACKAGE_PIN W40            [get_ports {SFP_RS0[0]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS0[0]}]
#set_property PACKAGE_PIN Y40            [get_ports {SFP_RS1[0]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS1[0]}]
set_property PACKAGE_PIN AB41           [get_ports {SFP_TX_DISABLE[0]}]
set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_DISABLE[0]}]
#set_property PACKAGE_PIN Y38            [get_ports {SFP_TX_FAULT[0]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_FAULT[0]}]
set_property PACKAGE_PIN AN5            [get_ports {SFP_RX_N[0]}]
set_property PACKAGE_PIN AN6            [get_ports {SFP_RX_P[0]}]

set_property PACKAGE_PIN AP3            [get_ports {SFP_TX_N[0]}]
set_property PACKAGE_PIN AP4            [get_ports {SFP_TX_P[0]}]


#set_output_delay -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports SFP_LOS_0]
#set_output_delay -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports SFP_LOS_0]

#SFP2
#set_property PACKAGE_PIN AA40           [get_ports {SFP_LOS[1]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_LOS[1]}]
#set_property PACKAGE_PIN AA42           [get_ports {SFP_MOD_DETECT[1]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_MOD_DETECT[1]}]
#set_property PACKAGE_PIN AB38           [get_ports {SFP_RS0[1]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS0[1]}]
#set_property PACKAGE_PIN AB39           [get_ports {SFP_RS1[1]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS1[1]}]
set_property PACKAGE_PIN Y42            [get_ports {SFP_TX_DISABLE[1]}]
set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_DISABLE[1]}]
#set_property PACKAGE_PIN AA39           [get_ports {SFP_TX_FAULT[1]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_FAULT[1]}]
set_property PACKAGE_PIN AM7            [get_ports {SFP_RX_N[1]}]
set_property PACKAGE_PIN AM8            [get_ports {SFP_RX_P[1]}]
set_property PACKAGE_PIN AN1            [get_ports {SFP_TX_N[1]}]
set_property PACKAGE_PIN AN2            [get_ports {SFP_TX_P[1]}]

#SFP3
#set_property PACKAGE_PIN AD38           [get_ports {SFP_LOS[2]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_LOS[2]}]
#set_property PACKAGE_PIN AC39           [get_ports {SFP_MOD_DETECT[2]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_MOD_DETECT[2]}]
#set_property PACKAGE_PIN AD42           [get_ports {SFP_RS0[2]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS0[2]}]
#set_property PACKAGE_PIN AE42           [get_ports {SFP_RS1[2]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS1[2]}]
set_property PACKAGE_PIN AC38           [get_ports {SFP_TX_DISABLE[2]}]
set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_DISABLE[2]}]
#set_property PACKAGE_PIN AA41           [get_ports {SFP_TX_FAULT[2]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_FAULT[2]}]
set_property PACKAGE_PIN AL5            [get_ports {SFP_RX_N[2]}]
set_property PACKAGE_PIN AL6            [get_ports {SFP_RX_P[2]}]
set_property PACKAGE_PIN AM3            [get_ports {SFP_TX_N[2]}]
set_property PACKAGE_PIN AM4            [get_ports {SFP_TX_P[2]}]

#SFP4
#set_property PACKAGE_PIN AD40           [get_ports {SFP_LOS[3]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_LOS[3]}]
#set_property PACKAGE_PIN AC41           [get_ports {SFP_MOD_DETECT[3]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_MOD_DETECT[3]}]
#set_property PACKAGE_PIN AE39           [get_ports {SFP_RS0[3]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS0[3]}]
#set_property PACKAGE_PIN AE40           [get_ports {SFP_RS1[3]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_RS1[3]}]
set_property PACKAGE_PIN AC40           [get_ports {SFP_TX_DISABLE[3]}]
set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_DISABLE[3]}]
#set_property PACKAGE_PIN AC40           [get_ports {SFP_TX_FAULT[3]}]
#set_property IOSTANDARD LVCMOS18        [get_ports {SFP_TX_FAULT[3]}]
set_property PACKAGE_PIN AJ5            [get_ports {SFP_RX_N[3]}]
set_property PACKAGE_PIN AJ6            [get_ports {SFP_RX_P[3]}]
set_property PACKAGE_PIN AL1            [get_ports {SFP_TX_N[3]}]
set_property PACKAGE_PIN AL2            [get_ports {SFP_TX_P[3]}]

#GPIO LEDs
set_property PACKAGE_PIN AM39 	 [get_ports {GPIO_LED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[0]}]
set_property PACKAGE_PIN AN39 	 [get_ports {GPIO_LED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[1]}]
set_property PACKAGE_PIN AR37 	 [get_ports {GPIO_LED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[2]}]
set_property PACKAGE_PIN AT37 	 [get_ports {GPIO_LED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[3]}]
set_property PACKAGE_PIN AR35 	 [get_ports {GPIO_LED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[4]}]
set_property PACKAGE_PIN AP41 	 [get_ports {GPIO_LED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[5]}]
set_property PACKAGE_PIN AP42 	 [get_ports {GPIO_LED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[6]}]
set_property PACKAGE_PIN AU39 	 [get_ports {GPIO_LED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_LED[7]}]

#DIP
set_property PACKAGE_PIN AV30 	 [get_ports {GPIO_DIP[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[0]}]
set_property PACKAGE_PIN AY33 	 [get_ports {GPIO_DIP[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[1]}]
set_property PACKAGE_PIN BA31 	 [get_ports {GPIO_DIP[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[2]}]
set_property PACKAGE_PIN BA32 	 [get_ports {GPIO_DIP[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[3]}]
set_property PACKAGE_PIN AW30 	 [get_ports {GPIO_DIP[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[4]}]
set_property PACKAGE_PIN AY30 	 [get_ports {GPIO_DIP[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[5]}]
set_property PACKAGE_PIN BA30 	 [get_ports {GPIO_DIP[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[6]}]
set_property PACKAGE_PIN BB31 	 [get_ports {GPIO_DIP[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO_DIP[7]}]

#CPU RESET
set_property PACKAGE_PIN AV40    [get_ports CPU_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_RESET]

#set_input_delay -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports CPU_RESET]
#set_input_delay -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports CPU_RESET]

#USB UART
set_property PACKAGE_PIN AU36    [get_ports USB_UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_RX]
set_property PACKAGE_PIN AU33    [get_ports USB_UART_TX]
set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_TX]
#set_property PACKAGE_PIN AR34 [get_ports USB_UART_CTS]
#set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_CTS]
#set_property PACKAGE_PIN AT32 [get_ports USB_UART_RTS]
#set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_RTS]


#set_output_delay -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports USB_UART_RX]
#set_output_delay -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports USB_UART_RX]

#IIC
set_property PACKAGE_PIN AY42 [get_ports IIC_MUX_RESET_B_LS]
set_property IOSTANDARD LVCMOS18 [get_ports IIC_MUX_RESET_B_LS]
set_property PACKAGE_PIN AT35 [get_ports IIC_SCL_MAIN_LS]
set_property IOSTANDARD LVCMOS18 [get_ports IIC_SCL_MAIN_LS]
set_property PACKAGE_PIN AU32 [get_ports IIC_SDA_MAIN_LS]
set_property IOSTANDARD LVCMOS18 [get_ports IIC_SDA_MAIN_LS]


#set_output_delay -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports IIC_MUX_RESET_B_LS]
#set_output_delay -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports IIC_MUX_RESET_B_LS]
#set_input_delay  -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports IIC_SCL_MAIN_LS]
#set_input_delay  -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports IIC_SCL_MAIN_LS]
#set_output_delay -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports IIC_SDA_MAIN_LS]
#set_output_delay -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports IIC_SDA_MAIN_LS]

#FAN
set_property PACKAGE_PIN BA37 [get_ports SM_FAN_PWM]
set_property IOSTANDARD LVCMOS18 [get_ports SM_FAN_PWM]
#set_property PACKAGE_PIN BB37 [get_ports SM_FAN_TACH]
#set_property IOSTANDARD LVCMOS18 [get_ports SM_FAN_TACH]

set_output_delay -clock [get_clocks drpclk_in_i] -min -0.000 [get_ports SM_FAN_PWM]
set_output_delay -clock [get_clocks drpclk_in_i] -max  1.000 [get_ports SM_FAN_PWM]

#SI5324 REC_CLOCK
#set_property PACKAGE_PIN AW33 [get_ports REC_CLOCK_C_N]
#set_property IOSTANDARD LVDS [get_ports REC_CLOCK_C_N]
#set_property PACKAGE_PIN AW32 [get_ports REC_CLOCK_C_P]
#set_property IOSTANDARD LVDS [get_ports REC_CLOCK_C_P]

#GPIO P.B. SW
set_property PACKAGE_PIN AV39 [get_ports GPIO_SW_C]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_C]
#set_property PACKAGE_PIN AU38 [get_ports GPIO_SW_E]
#set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_E]
#set_property PACKAGE_PIN AR40 [get_ports GPIO_SW_N]
#set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_N]
#set_property PACKAGE_PIN AP40 [get_ports GPIO_SW_S]
#set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_S]
#set_property PACKAGE_PIN AW40 [get_ports GPIO_SW_W]
#set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_W]